apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
data:
  fluent-bit.conf: |
    [SERVICE]
        flush        1
        daemon       Off

    [INPUT]
        Name              tail
        Path              /mnt/log/*

    [OUTPUT]
        name  opensearch
        match *
        host 10.0.21.195
        port 9200
        tls On
        HTTP_User elastic
        HTTP_Passwd wNKhoWtnh9_Emm9
        Index fluent-bit
        Suppress_Type_Name On
---
apiVersion: v1
kind: Pod
metadata:
  name: date-logging
spec:
  containers:
  - name: date
    image: busybox
    resources:
      requests:
        cpu: 500m
        memory: 200Mi
    command: ["sh", "-c"]
    args:
      - while [ 1 ]; do
        echo "Writing the date in /mnt/log/date.log";
        date >> /mnt/log/date.log;
        sleep 10;
        done
    volumeMounts:
    - name: logs
      mountPath: /mnt/log
  - name: logging
    image: fluent/fluent-bit
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
    volumeMounts:
    - name: logs
      mountPath: /mnt/log
    - name: fluentbit-config
      mountPath: /fluent-bit/etc
  volumes:
  - name: logs
    emptyDir: {}
  - name: fluentbit-config
    configMap:
      name: fluentbit-config